name: flutter_firebase_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  http: ^0.13.0
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  bloc: ^8.1.0
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  
  hive_generator: ^1.1.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


